
install.packages("dichromat")
install.packages("e1071")
install.packages("labeling")
install.packages("minqa")
install.packages("nloptr")
install.packages("plyr")
install.packages("randomForest")
install.packages("RColorBrewer")
install.packages("reshape2")
install.packages("rpart")
install.packages("tree")
install.packages("nnet")
install.packages("car")
install.packages("caret")
